// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfw1T0fToND3GbLhwlZkMStamTrPbYLpA',
    appId: '1:588925586601:web:0b3cada622ef4949caadb8',
    messagingSenderId: '588925586601',
    projectId: 'prajwalnotes',
    authDomain: 'prajwalnotes.firebaseapp.com',
    storageBucket: 'prajwalnotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgnk2vfRmLvqWnT1HVv1h59zTUYV784cU',
    appId: '1:588925586601:android:b599847c98b41ca8caadb8',
    messagingSenderId: '588925586601',
    projectId: 'prajwalnotes',
    storageBucket: 'prajwalnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI4OGzRUvgsxOO0BLeHWHtZuSIVNMgznY',
    appId: '1:588925586601:ios:8817569630689b44caadb8',
    messagingSenderId: '588925586601',
    projectId: 'prajwalnotes',
    storageBucket: 'prajwalnotes.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI4OGzRUvgsxOO0BLeHWHtZuSIVNMgznY',
    appId: '1:588925586601:ios:8817569630689b44caadb8',
    messagingSenderId: '588925586601',
    projectId: 'prajwalnotes',
    storageBucket: 'prajwalnotes.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfw1T0fToND3GbLhwlZkMStamTrPbYLpA',
    appId: '1:588925586601:web:b6724ba56e3fc3e2caadb8',
    messagingSenderId: '588925586601',
    projectId: 'prajwalnotes',
    authDomain: 'prajwalnotes.firebaseapp.com',
    storageBucket: 'prajwalnotes.appspot.com',
  );

}